# For demo purposes we use cloud versions of Mongo and RabbitMQ
spring:

  # mlab.com: server.product.travelport / changeit123!!!
  data:
    mongodb:
      uri: mongodb://user:password123@ds137600.mlab.com:37600/persons

  # cloudamqp.com: server.product.travelport@gmail.com / changeit!!!
  rabbitmq:
    host: duckbill.rmq.cloudamqp.com
    username: atfeadmf
    password: L1soAOkSmtPbQFvy08af47hec-I8_jcN
    virtual-host: atfeadmf

service-glossary:
  minimum-allocatable-id: 5000
  jenkins-address: https://system-jenkins.build.mttnow.com
  git:
    baseAddr: http://bitbucket.org/mttnow/

logging:
  level:
    com.travelport.service.glossary: DEBUG
    com.travelport.service.glossary.service: TRACE
    com.travelport.service.glossary.metrics: INFO
